### PR TITLE
Make it a noop in Ember > 3.0.0-beta.2

### LINKED ISSUE #18: Exception thrown in Ember canary (3.1)
The exception is that `this._bubbleEvent` is not a function:
https://github.com/rwjblue/ember-native-dom-event-dispatcher/blob/8c105061b8455e6f00015572cc5699b3e5045519/addon/index.js#L72

Steps to reproduce it:
1. Clone https://github.com/cibernox/ember-basic-dropdown
2. Update to canary: `"ember-source": "http://builds.emberjs.com/canary/daily/20180110.tgz",`
3. Boot the app without fastboot (which is also broken): `FASTBOOT_DISABLED=true ember serve`
4. Interact with the dropdown in the top of the page and see the error being logged many times.

### PR DESCRIPTION
**Pull request by cibernox**
Closes #18

Would you also output a console warning asking users to just remove the addon?
Also, should it be `gt('3.0.0-beta.2');` or `gte('3.0.0-beta.2');`?

### CODE REVIEW

**Comment by rwjblue** [comment]
> should it be gt('3.0.0-beta.2'); or gte('3.0.0-beta.2');?

I think gte would work, but I can't recall if ember-cli-version-checker exposes a `.gte` 😝

**Comment by rwjblue** [comment]
> Would you also output a console warning asking users to just remove the addon?

[This](https://github.com/rwjblue/ember-router-service-polyfill/blob/v1.0.2/index.js#L20-L23) is what I have done in the past, but it makes annoying warnings for addons during ember-try scenarios.

Maybe we can tweak the logic to be:

```js
    this._shouldDisable = true;
    if (emberVersion.lt('3.0.0-beta.2')) {
      this._shouldDisable = false;
    } else if (this.parent === this.project && !process.env.EMBER_TRY_CURRENT_SCENARIO){
      this.ui.writeWarnLine('ember-native-dom-event-dispatcher is not required for Ember 3.0.0-beta.2 and later, please remove from your `package.json`.');
    }
```

Adding the check for `EMBER_TRY_CURRENT_SCENARIO` should alleviate some of @Turbo87's prior concerns (RE: https://github.com/rwjblue/ember-getowner-polyfill/issues/16)...

**Comment by cibernox** [comment]
Done. It works pretty well and only outputs once.

**Comment by rwjblue** [comment]
Merging this, would you mind sending another PR updating the README to explain that this addon is not needed with Ember 3.0?

**Pull request merged**
