### PR TITLE
Not working for unit tests

### PR DESCRIPTION
**Pull request by cibernox**
Based on top of #6

### CODE REVIEW

**Comment by rwjblue** [comment]
Probably needs a rebase now that #6 landed.

**Comment by cibernox** [comment]
Done, sir.

**Comment by stefanpenner** [comment]
CI appears unhappy

**Comment by rwjblue** [comment]
We should totally get this fixed if possible, but using `unit: true` or `needs: []` will be deprecated sometime soon.

**Comment by rwjblue** [comment]
Closing for now, this should be working properly now...

**Pull request closed without merging**
